---
- name: Wait for instances to become reachable
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for instances to become reachable
      wait_for_connection:
        delay: 10
        sleep: 10
        timeout: 120
      tags:
        - linux_install

- name: Collect DC/OS versions
  hosts: all
  tasks:
    - name: Collect DC/OS versions
      setup:
      tags:
        - linux_install

- name: DC/OS Requirements
  hosts: all
  become: true
  tasks:
    - include_role:
        name: dcos_requirements
    - include_role:
        name: dcos_gpu
      tags:
        - linux_install

- name: Setup and configure BOOTSTRAP nodes
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: dcos_bootstrap
      tags:
        - linux_install

- name: Setup and configure MASTER nodes
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: dcos_master
      tags:
        - linux_install

- name: Setup and configure AGENT nodes (Linux)
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: dcos_agent
      tags:
        - linux_install

- name: Setup and configure AGENT nodes (Windows)
  hosts: win_agents
  tasks:
    - include_role:
        name: dcos_agent_windows
      tags:
        - windows_install
