- name: DC/OS Requirements
  hosts: all
  become: true
  tasks:
    - include_role:
        name: DCOS.requirements

- name: "Setup and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: DCOS.bootstrap

- name: "Setup and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master

- name: "Setup and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
