---
# This playbook deploys dcos on-premise.

- name: apply common configuration to all nodes
  hosts: all
  serial: 10
  sudo: yes

  roles:
    - common

- name: generate the DC/OS configuration
  hosts: workstations
  serial: 10
  sudo: yes

  roles:
    - workstation

- name: deploy DCOS masters
  hosts: masters
  serial: 10
  sudo: yes

  roles:
    - master

- name: deploy DCOS agents
  hosts: agents
  serial: 10
  sudo: yes

  roles:
    - agent

- name: deploy DCOS public agents
  hosts: agents_public
  serial: 10
  sudo: yes

  roles:
    - agent_public
