---
# This playbook deploys DC/OS

- name: apply common configuration to all nodes
  hosts: all
  serial: 20
  become: true

  roles:
    - common

- name: generate the DC/OS configuration
  hosts: bootstraps
  serial: 20
  become: true

  roles:
    - bootstrap

- name: deploy nodes
  hosts: [ masters, agents, agents_public]
  serial: 20
  become: true

  roles:
    - node-install
