---
# This playbook deploys dcos on-premise.

- name: apply common configuration to all nodes
  hosts: all
  sudo: yes

  roles:
    - common

- name: starts ZooKeeper for bootstrapping and generates the DC/OS configuration
  sudo: yes
  hosts: workstations

  roles:
    - workstation

- name: deploy DCOS masters
  sudo: yes
  hosts: masters

  roles:
    - master

- name: deploy DCOS agents
  sudo: yes
  hosts: agents

  roles:
    - agent

- name: deploy DCOS public agents
  sudo: yes
  hosts: agents_public

  roles:
    - agent_public
