dcos_docker_pkg_name: docker-ce
dcos_docker_repo_name: docker-ce-stable
dcos_prereq_packages:
  - tar
  - xz
  - unzip
  - curl
  - ipset
  - jq # not technically required by DC/OS but by this Ansible role for checks

