---
# This playbook deploys the dcos agent nodes

- file: path=/tmp/dcos/ state=directory mode=0755

- get_url: url="http://{{ workstation_ip }}:8080/dcos_install.sh" dest=/tmp/dcos/dcos_install.sh mode=0440

- shell: cd /tmp/dcos/; sudo bash dcos_install.sh slave_public
  ignore_errors: yes
