---
- name: DC/OS Requirements
  hosts: all
  become: true
  tasks:
    - include_role:
        name: DCOS.requirements

- name: "Setup and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - debug:
        var: hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address
    - debug:
        var: hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address
    - include_role:
        name: DCOS.bootstrap
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]

- name: "Setup and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]

- name: "Setup and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
  vars:
    dcos:
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]


- name: "WAIT for the cluster to stabilise before upgrade"
  hosts: localhost
  tasks:
    - name: WAIT for the cluster to stabilise before upgrade
      pause:
        minutes: 1

- name: "Upgrade and configure BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: DCOS.bootstrap
  vars:
    dcos:
      download: "https://downloads.dcos.io/dcos/testing/1.12/commit/3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623/dcos_generate_config.sh"
      version: "1.12.0"
      version_to_upgrade_from: "1.12.0"
      image_commit: "3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]

- name: "Upgrade and configure MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master
  vars:
    dcos:
      download: "https://downloads.dcos.io/dcos/testing/1.12/commit/3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623/dcos_generate_config.sh"
      version: "1.12.0"
      version_to_upgrade_from: "1.12.0"
      image_commit: "3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]

- name: "Upgrade and configure AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
  vars:
    dcos:
      download: "https://downloads.dcos.io/dcos/testing/1.12/commit/3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623/dcos_generate_config.sh"
      version: "1.12.0"
      version_to_upgrade_from: "1.12.0"
      image_commit: "3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]


- name: "WAIT for the cluster to stabilise before same-version-config-update"
  hosts: localhost
  tasks:
    - name: WAIT for the cluster to stabilise before upgrade
      pause:
        minutes: 1

- name: "Same-version-config update BOOTSTRAP nodes"
  hosts: bootstraps
  become: true
  tasks:
    - include_role:
        name: DCOS.bootstrap
  vars:
    dcos:
      download: "https://downloads.dcos.io/dcos/testing/1.12/commit/3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623/dcos_generate_config.sh"
      version: "1.12.0"
      version_to_upgrade_from: "1.12.0"
      image_commit: "3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]
        resolvers: [1.1.1.1]

- name: "Same-version-config update MASTER nodes"
  hosts: masters
  serial: 1
  become: true
  tasks:
    - include_role:
        name: DCOS.master
  vars:
    dcos:
      download: "https://downloads.dcos.io/dcos/testing/1.12/commit/3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623/dcos_generate_config.sh"
      version: "1.12.0"
      version_to_upgrade_from: "1.12.0"
      image_commit: "3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]
        resolvers: [1.1.1.1]

- name: "Same-version-config update AGENT nodes"
  hosts: agents
  become: true
  tasks:
    - include_role:
        name: DCOS.agent
  vars:
    dcos:
      download: "https://downloads.dcos.io/dcos/testing/1.12/commit/3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623/dcos_generate_config.sh"
      version: "1.12.0"
      version_to_upgrade_from: "1.12.0"
      image_commit: "3b8b3837cd12bdbc0853e5cd9e0d635b8ba83623"
      config:
        bootstrap_url: "http://{{ hostvars[groups['bootstraps'][0]].ansible_facts.eth1.ipv4.address }}:8080"
        master_list: ["{{ hostvars[groups['masters'][0]].ansible_facts.eth1.ipv4.address }}"]
        resolvers: [1.1.1.1]
