- hosts: [ masters, agents, agents_public]
  become: true
  tasks:

    - name: DC/OS uninstall
      shell: sudo -i /opt/mesosphere/bin/pkgpanda uninstall
      ignore_errors: true

    - name: remove DC/OS configuration
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /opt/mesosphere
        - /etc/mesosphere
        - /var/lib/mesosphere
        - /var/lib/dcos
        - /var/lib/zookeeper
        - /var/lib/mesos
        - /tmp/dcos/
        - /run/dcos/
        - /run/mesos
        - /var/log/mesos
        - /etc/profile.d/dcos.sh
        - /etc/systemd/journald.conf.d/dcos.conf
        - /etc/systemd/system/dcos-download.service
        - /etc/systemd/system/dcos-link-env.service
        - /etc/systemd/system/dcos-setup.service
        - /etc/systemd/system/multi-user.target.wants/dcos-setup.service
        - /etc/systemd/system/multi-user.target.wants/dcos.target
        - /etc/systemd/system/dcos.target
        - /etc/systemd/system/dcos.target.wants

    - name: reload systemd
      shell: systemctl daemon-reload
      ignore_errors: true

- hosts: bootstraps
  become: true
  tasks:

    - name: Stop Nginx
      docker_container:
        name: dcos_nginx
        state: absent

    - name: Clear install directory
      file: path=/var/lib/dcos-bootstrap state=absent
      ignore_errors: true
