---
# This playbook performs a DC/OS upgrade

- name: setup the system requirements on all nodes
  hosts: all
  serial: 20
  become: true

  roles:
    - common
    - docker

- name: generate upgrade configuration
  hosts: bootstraps
  serial: 1
  become: true

  vars:
    upgrade: true
    installed_cluster_version: 1.9.4

  roles:
    - bootstrap

- name: upgrade masters
  hosts: masters
  serial: 1
  become: true

  roles:
    - node-upgrade

- name: upgrade agents
  hosts: [ agents, agents_public]
  serial: 20
  become: true

  roles:
    - node-upgrade
