---
# This playbook contains common plays that will be run on all nodes.

# Update system
- yum: name=* state=latest

# Install docker
- template: src=docker.repo dest=/etc/yum.repos.d/docker.repo mode=0644
- file: path=/etc/systemd/system/docker.service.d/ state=directory mode=0755
- template: src=override.conf dest=/etc/systemd/system/docker.service.d/override.conf mode=0644
- yum: name=docker-engine update_cache=yes state=latest
- service: name=docker enabled=yes
- service: name=docker state=started
- user: name="{{ remote_user }}" groups=docker append=yes

# Install utilities
- yum: name=tar state=latest
- yum: name=xz state=latest
- yum: name=unzip state=latest
- yum: name=curl state=latest

# Cluster permissions
- selinux: policy=targeted state=permissive
- group: name=nogroup state=present
- sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 sysctl_set=yes
- sysctl: name="net.ipv6.conf.default.disable_ipv6" value=1 sysctl_set=yes
